### ISSUE TITLE
firmware v7 wrongly calibrated

### ISSUE THREAD

**Issue by ernstkl** [watterott/CO2-Ampel#1]
Hello,

the firmware v7 displays a CO2 ppm value of ca. 220 ppm in a well ventilated office. This is not plausible as fresh air has about 400 ppm CO2.
Doing the check outside, the ppm value drops to zero.

This looks like a wrong calibration to me. According to the readme, doing a calibration usually is not required.

**Comment by ernstkl** [comment]
need to check, maybe we miscalibrated ourselves, sorry.

**Comment by awatterott** [comment]
Please contact us via mail: support at watterott dot com
