### ISSUE TITLE
Wifi connection crashes after 1 1/2 day running

### ISSUE THREAD

**Issue by HaeckslerSXS** [watterott/CO2-Ampel#13]
We bought this sensor to messure CO2 in our office, unfortunately the Wifi connection crashes frequently.
We think it would help I we would have the possibility to enter a fix IP.

**Comment by awatterott** [comment]
Can you please contact us by email to troubleshoot the problem/issue at first:
https://shop.watterott.com/Contact
We have seen a similar behavior with Ubiquiti devices with an old firmware.
