### ISSUE TITLE
Could you provide "without buzzer" releases, please?

### ISSUE THREAD

**Issue by ldidry** [watterott/CO2-Ampel#17]
The last firmware releases on https://learn.watterott.com/breakouts/co2-ampel/firmware/ don't have "without buzzer" versions. Could you provide such versions, please?

Thank you.

**Comment by awatterott** [comment]
With v22+ the buzzer can be deactivated/activated via the [service menu](https://learn.watterott.com/breakouts/co2-ampel/getting-started/#service-menu). In the future it is also planned that the settings from the service menu can be changed via the webinterface.

**Comment by ldidry** [comment]
Thank you very much!

**Comment by ernstkl** [comment]
@ldidry If you do not mind flashing the firmware yourself, you could use [my fork](https://github.com/ernstkl/CO2-Ampel). It adds some convenience features, including pushing up the buzzer threshold to an arbitrarily high value, via the web interface. (I could not find a different way to contact you than writing here)
