### ISSUE TITLE
Hysterese?

### ISSUE THREAD

**Issue by mschlenker** [watterott/CO2-Ampel#18]
In unserem Unternehmen nutzen wir einige CO2-Ampeln für die Überwachung der Luftqualität (wofür sonst...). Leider haben wir festgestellt, dass das Lüftungsverhalten gerade so ist, dass die Schotten wieder dicht gemacht werden, wenn die Ampel gerade so wieder grün ist (oder die Email mit "WARN -> OK" kommt). Für das Checkmk-Plugin bin ich daher dabei, einen Hysteresefaktor als festen Prozentsatz einstellbar zu machen.

D.h., wenn der Übergang OK -> WARN bei Überschreiten von 1000ppm stattfindet und ein Hysteresefaktor von 10% eingestellt ist, findet der Übergang von WARN -> OK erst statt, wenn 900ppm unterschritten werden.

Wenn Ihr daran interessiert seid, den Code für die Hysterese zu übernehmen, werde ich den Code entsprechend sauber strukturieren und gut kommentieren und dann als Pull-Request einreichen. Wäre das in Eurem Interesse?

Liebe Grüße
Mattias

**Comment by awatterott** [comment]
Zur Orientierung für das Ende einer Lüftung dient der blaue Bereich (<600ppm).

**Comment by mschlenker** [comment]
Hallo Andreas,

Das ist der Idealfall und letztendlich eine Interpretation einer extremen Hysterese. In vielen Umgebungen bedeutet das sehr lange Lüftungszeiten. ASR 3.6 ist zwischen 1000ppm und 2000ppm auch recht flexibel. Ich teste unsere Hysterese nächste Woche mal auf der Checkmk Konferenz und gebe dann nochmal Feedback.

Schönen Abend!
Mattias
