### ISSUE TITLE
Unpopulated component J2 next to Qwiic connector?

### ISSUE THREAD

**Issue by reibuehl** [watterott/CO2-Ampel#2]
I noticed that there is an unpopulated component, J2, next to the Qwiic connector J4 on the v1.1 board. Is there any information about what was supposed to be there?

**Comment by awatterott** [comment]
Its a SWD connector for programming/debugging:
https://github.com/watterott/CO2-Ampel/blob/master/hardware/CO2-Ampel_v11.pdf
Please use our support mail address for technical questions.
