### ISSUE TITLE
Where should documentation issues be handled ?

### ISSUE THREAD

**Issue by olberger** [watterott/CO2-Ampel#4]
This repo seems to be about the hardware / firmware, so it's not clear if issues relating to docs at https://learn.watterott.com/breakouts/co2-ampel/ should be part of the perimeter.

Could you clarify ?

IMHO, it would be great to have the docs inside the same GitHub project (or another one ?), so that one can report issue, contribute etc. instead of having them on a separate site.

**Comment by awatterott** [comment]
The documentations of our learn website are not available on GitHub and issues or improvements can be submitted via mail.

**Comment by olberger** [comment]
Would you mind providing the corresponding email address ?

**Comment by awatterott** [comment]
info - at - watterott - dot - com
https://shop.watterott.com/Contact
