### ISSUE TITLE
Firmware co2_covid_v11.bin doesn't seem to work well with v1.1 standard device

### ISSUE THREAD

**Issue by olberger** [watterott/CO2-Ampel#5]
I have tested the co2_covid_v11.bin firmware from
https://learn.watterott.com/breakouts/co2-ampel/getting-started/co2_covid_v11.bin and values reported over the USB serial port (and light colors) seem to be varying to erratically, on my v1.1 standard version.

Firmware co2_covid_v10.bin seems more reliable (smoother evolution of CO2 level).

Maybe this is known : "could cause freezing of standard version on startup (since v5)" seems to indicate a problem with the standard version... or I misunderstand the meaning of that notice : not clear if it applies to the prior versions (bug fixed), or is a known issue with that update... proper changelog/release notes would help (maybe not in the getting started page, but couldn't find more docs...)

Thanks in advance.

**Comment by awatterott** [comment]
The different between v10 and v11 is just a fix for the possible freezing, which was caused by the detection code for the plus version.

**Comment by olberger** [comment]
OK, so what about the fact that v11 doesn't report values in a sensible way ?

It's no big deal, but may I complain a bit about the quickly closed issues I've just experienced. Please, don't close issues when you responded only to the last sentence, and when the initial part of my issue (and the summary) is the real problem...

It looks like you're worried about issues open... and seems a bit rude for the reporter (who's also a customer FWIW)... I'm just trying to help, and not blaming specifically, but I tend to feel like the issues aren't address somehow.

Or just that's not the place for such discussion... sorry then, but there doesn't seem to be any proper docs about how to report issues anywhere... so... again I don't want to be rude either to you, but it's just a bit confusing without more details on the expected procedures... 

Thanks in advance / Vielen Dank.

**Comment by awatterott** [comment]
The CO2 values over USB are directly from the SCD30 sensor and the LEDs show an average of those values, which will lead the LEDs to a slower reaction.
Note, with enabled remote mode the measurement interval will be 2s and the default is 3s.
But this is not an issue and if you have technical questions then please contact us via mail.
