### ISSUE TITLE
Update instructions aren't clear

### ISSUE THREAD

**Issue by olberger** [watterott/CO2-Ampel#6]
https://learn.watterott.com/breakouts/co2-ampel/getting-started/#update-instructions isn't clear on what's needed for updating the firmware.

I seem to have managed to update by just copying the "co2_covid_v10.bin" file into /media/.../CO2AMPEL/ with a file manager on Linux, without the need to use dd (which actually reports an error on a non existant file)

Also, as there's no APP.BIN file to be downloaded so maybe it would be more realistic to provide something like :
```
cp co2_covid_vNN.bin /media/CO2AMPEL/ 
```
or I don't understand the naming scheme at stake (not clear what the existing CURRENT.BIN file is, once the USB mass storage appears)

Thanks in advance

**Comment by awatterott** [comment]
For the update a copy of the firmware file to the mass storage drive is needed.
`APP.BIN` is an example file name and `dd` will copy the file in one stream, which is the best way for the [bootloader](https://github.com/microsoft/uf2-samdx1) to receive the data.
`CURRENT.BIN` contains the current firmware.

**Comment by olberger** [comment]
OK, It looks like our conversation seem to be happening with different documentation purposes. I really fail to understand the level of details in your comments compared to the kind of user manual I'm expecting in products usually... probably different culture, expectations, practicies of FLOSS documentation.

I'm quite disappointed.

Thanks anyway.

**Comment by awatterott** [comment]
I'm quite disappointed, because you opened one issue after another without waiting a reasonable time for an answer to clarify how we handle technical support or issues/improvements on documentations.

**Comment by olberger** [comment]
OK, obviously there's a misunderstanding on the role of the issue tracker in this repo... which is quite normal if things aren't stated explicitely.

My advice would be either to shut the tracker if you don't intend to use it (fine), or make some kind of statement in the readme (or in the tracker config ?) to explicitely state what kind of requests are expected.

Also, maybe some notice on the docs side on how to report issues, questions, support requests and such... and also whether the GitHub repo is or isn't the place to refer to : are "regular users" welcome to use it ir is it mainly for developpers.

Of course, I didn't ask first, and didn't wait... and on the other hand I hadn't much time to dedicate to my expertiments and wouldn't want to wait... and I'm not sure there was a hurry in closing your issues either... unless I misunderstand your context. IMHO having open issues on a repo isn't shamefull, etc.

Anyway, thanks for the explicitation, and wishing you best luck in future handling of impatient users ;)
