### ISSUE TITLE
No values detected on serial link until I flashed the v10+ firmware

### ISSUE THREAD

**Issue by olberger** [watterott/CO2-Ampel#7]
Is there a known issue (undocumented ?) on standard device which could become silent over serial ?

I seem to had proper serial config with cutecom and /dev/ttyACM0 (9600, 8-N1 etc.) but couldn't detect anything on the serial line. Leds were working fine (supposedly, changing to green when getting fresh air, etc.)

After I flashed the v11 firmware, it suddenly started to report sensor values.

Also I couldn't figure out how to detect which version of firmware was running initially as shipped from the store... but that's probably another issue ;-)

**Comment by awatterott** [comment]
With v10 the USB detection was changed and previously flow control was used via Arduino Serial functions, which only works directly with the Arduino IDE.
https://github.com/watterott/CO2-Ampel/blob/master/arduino/samd/libraries/CO2-Ampel/examples/CO2-Ampel/CO2-Ampel.ino#L1284
There is currently no command to receive the version of the firmware.

**Comment by olberger** [comment]
Uh, sorry but I fail to understand if the above response is supposed to explain why I couldn't see any traffic on the USB serial... Could you explain for someone without knowledge of Arduino stuff ?

**Comment by awatterott** [comment]
If the firmware/CO2-Ampel does not detect a USB host device, then no data will be sent via the USB serial port.
