### ISSUE TITLE
Provide basic "generic" shell script for monitoring sensor values over USB/serial

### ISSUE THREAD

**Issue by olberger** [watterott/CO2-Ampel#8]
Would it be possible to provide (in this repo ?) a basic shell script that could be generic enough to work on most Linux distros, to read sensor values over /dev/ttyACM0 (serial USB) ?

The docs in https://learn.watterott.com/breakouts/co2-ampel/getting-started/#serial-interface-usb point to the HTerm program, with a nice GUI etc. but for simple testing, I guess some stty / screen and such could be widely available on Linux boxes.

Thanks in advance.

**Comment by awatterott** [comment]
We have updated the documentation, but there are no plans for making a script.
Screen can also be used for the readout: `screen /dev/ttyACM0 9600`
